runtime: nodejs22
env: standard
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_idle_instances: 1
handlers:
  - url: /assets
    static_dir: dist/assets
    redirect_http_response_code: 301
    secure: always
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
    redirect_http_response_code: 301
    secure: always
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    redirect_http_response_code: 301
    secure: always
