service: backend
runtime: nodejs16
env: standard
instance_class: F1
automatic_scaling:
  min_instances: 0
inbound_services:
  - warmup
handlers:
  - url: .*
    script: auto
    redirect_http_response_code: 301
    secure: always
