on:
  pull_request:
    paths:
      - "backend/**"

jobs:
  build_backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: actions/setup-node@v3
      - run: npm ci
