on:
  pull_request:
    paths:
      - "clone/**"
      - "common/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/build_clone.yml"

jobs:
  build_clone:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build app
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci -w common -w clone
      - run: npm run test -w common -w clone
      - run: npm run format -w common -w clone
      - run: npm run lint -w common -w clone
      - run: npm run build
        working-directory: common
      - run: npm run build
        working-directory: clone
