on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_clone:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    concurrency:
      group: clone
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci -ws
      - run: npm run build
        working-directory: common
      - run: npm run build
        working-directory: clone

      - name: Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy
        uses: "google-github-actions/deploy-cloud-functions@v3"
        with:
          name: clone-timetable
          runtime: nodejs22
          region: europe-central2
          source_dir: clone/dist
          entry_point: clone-timetable
