on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_functions:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    concurrency:
      group: functions
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy
        uses: "google-github-actions/deploy-cloud-functions@v3"
        with:
          name: clone-timetable
          runtime: nodejs22
          region: europe-central2
          source_dir: functions
          entry_point: clone-timetable
