on:
  workflow_dispatch:

jobs:
  deploy_cloud_function:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    concurrency:
      group: cloud-functions
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
