on:
  workflow_dispatch:

jobs:
  deploy_backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    permissions:
      contents: read
      id-token: write

    concurrency:
      group: backend
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: actions/setup-node@v3
      - run: npm ci

      - name: Auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy
        uses: "google-github-actions/deploy-appengine@v1.1.0"
        with:
          working_directory: backend
          version: "v0-1-0"
